"""Frontend + brand-asset serving (the non-/api routes).

Owns the resolved frontend paths; main imports FRONTEND_DIST_DIR from here for the
/assets mount. The /{filename} catch-all only matches single-segment paths, so it
never shadows the multi-segment /api/* routes regardless of include order.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse, Response

router = APIRouter()


def _default_frontend_dist() -> Path:
    # When frozen, PyInstaller unpacks bundled datas (the built web/ folder) under
    # sys._MEIPASS; the source-tree layout under apps/web/dist only exists in dev.
    meipass = getattr(sys, "_MEIPASS", None)
    if meipass:
        return Path(meipass) / "web"
    return FRONTEND_ROOT_DIR / "dist"


# This module sits at src/telemanager/routes/static.py, so the repo root is parents[3].
FRONTEND_ROOT_DIR = Path(__file__).resolve().parents[3] / "apps" / "web"
FRONTEND_DIST_DIR = Path(os.getenv("TELEMANAGER_FRONTEND_DIST_DIR", _default_frontend_dist()))
FRONTEND_PUBLIC_DIR = Path(os.getenv("TELEMANAGER_FRONTEND_PUBLIC_DIR", FRONTEND_ROOT_DIR / "public"))
NO_STORE_HEADERS = {"Cache-Control": "no-store"}


def first_existing(*paths: Path) -> Path:
    for path in paths:
        if path.exists():
            return path
    raise HTTPException(status_code=404, detail="File was not found.")


@router.get("/")
def index() -> Response:
    dist_index = FRONTEND_DIST_DIR / "index.html"
    if dist_index.exists():
        return FileResponse(dist_index, headers=NO_STORE_HEADERS)
    return Response(
        content="Build the React frontend with `npm run build` before serving the UI.",
        media_type="text/plain",
        status_code=503,
        headers=NO_STORE_HEADERS,
    )


@router.get("/favicon.ico")
def favicon_ico() -> FileResponse:
    return FileResponse(first_existing(FRONTEND_DIST_DIR / "favicon.ico", FRONTEND_PUBLIC_DIR / "favicon.ico"))


@router.get("/favicon.svg")
def favicon_svg() -> FileResponse:
    return FileResponse(first_existing(FRONTEND_DIST_DIR / "favicon.svg", FRONTEND_PUBLIC_DIR / "favicon.svg"))


# Root-level brand/PWA assets generated by scripts/gen-assets.mjs. Served from the
# built dist (preferred) or the public source dir. Whitelisted so this single-
# segment route can't be used to read arbitrary files. Registered after the
# explicit favicon routes so those keep priority; /api/* is two segments so it
# never matches here.
ROOT_STATIC_FILES = frozenset(
    {
        "favicon-16.png",
        "favicon-32.png",
        "apple-touch-icon.png",
        "icon-192.png",
        "icon-512.png",
        "og.png",
        "manifest.webmanifest",
    }
)


@router.get("/{filename}")
def root_static(filename: str) -> FileResponse:
    if filename not in ROOT_STATIC_FILES:
        raise HTTPException(status_code=404, detail="File was not found.")
    return FileResponse(first_existing(FRONTEND_DIST_DIR / filename, FRONTEND_PUBLIC_DIR / filename))
